# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stream_pb2 as stream__pb2


class StreamImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.imageStreaming = channel.stream_unary(
                '/StreamImage/imageStreaming',
                request_serializer=stream__pb2.imgReq.SerializeToString,
                response_deserializer=stream__pb2.imgResponse.FromString,
                )


class StreamImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def imageStreaming(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'imageStreaming': grpc.stream_unary_rpc_method_handler(
                    servicer.imageStreaming,
                    request_deserializer=stream__pb2.imgReq.FromString,
                    response_serializer=stream__pb2.imgResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StreamImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamImage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def imageStreaming(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/StreamImage/imageStreaming',
            stream__pb2.imgReq.SerializeToString,
            stream__pb2.imgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
